= Quarkus JGit

include::./includes/attributes.adoc[]

The Quarkus JGit extension enables the use of https://www.eclipse.org/jgit/[Eclipse JGit]
in a native executable.

== Configuration

Once you have your Quarkus project configured you can add the `jgit` extension to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="jgit"
----

First, add the `quarkus-jgit-bom` to your project's `<dependencyManagement>` section to ensure version alignment of all JGit dependencies:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.jgit</groupId>
    <artifactId>quarkus-jgit-bom</artifactId>
    <version>{quarkus-jgit-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

Then add the extension dependency without specifying a version:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.jgit</groupId>
    <artifactId>quarkus-jgit</artifactId>
</dependency>
----

== Usage

The https://wiki.eclipse.org/JGit/User_Guide#API[JGit] dependency is resolved transitively when the extension is added to your project.
Here is an example using it in a JAX-RS endpoint:

[source,java]
----
    @GET
    @Path("/clone")
    @Produces(MediaType.TEXT_PLAIN)
    public String cloneRepository(@QueryParam("url") String url) throws Exception {
        File tmpDir = Files.createTempDirectory("tmpgit").toFile();
        try (Git git = Git.cloneRepository().setDirectory(tmpDir).setURI(url).call()) {
            return tmpDir.toString();
        }
    }
----

[WARNING]
====
When building a native executable, make sure that the link:{quarkus-guides-url}/native-and-ssl#the-truststore-path[SSL support is configured appropriately].
====

== Git LFS Support

https://git-lfs.com/[Git Large File Storage (LFS)] is a Git extension that replaces large files (such as binaries, media assets, and datasets) with lightweight pointers in the repository, while storing the actual file contents on a remote server.

The extension automatically detects the presence of the JGit LFS module on the classpath and registers the necessary classes for native image compilation.

To enable Git LFS support, add the following dependency to your project:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.jgit</groupId>
    <artifactId>org.eclipse.jgit.lfs</artifactId>
</dependency>
----

No additional configuration is required.

== DevServices

JGit starts a link:https://about.gitea.com/[Gitea server] for testing purposes.
The server is disabled by default when running tests. To enable it, set the `quarkus.jgit.devservices.enabled` configuration property to `true`.

An admin user is created with the following credentials:

- Username: `quarkus`
- Password: `quarkus`

== Configuration properties

include::./includes/quarkus-jgit.adoc[]
