= Quarkus JGit

include::./includes/attributes.adoc[]

The Quarkus JGit extension enables the use of https://www.eclipse.org/jgit/[Eclipse JGit]
in a native executable.

== Configuration

Once you have your Quarkus project configured you can add the `jgit` extension to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="jgit"
----

This will add the following to your `pom.xml`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.jgit</groupId>
    <artifactId>quarkus-jgit</artifactId>
    <version>{quarkus-jgit-version}</version>
</dependency>
----

== Usage

The https://wiki.eclipse.org/JGit/User_Guide#API[JGit] dependency is resolved transitively when the extension is added to your project.
Here is an example using it in a JAX-RS endpoint:

[source,java]
----
    @GET
    @Path("/clone")
    @Produces(MediaType.TEXT_PLAIN)
    public String cloneRepository(@QueryParam("url") String url) throws Exception {
        File tmpDir = Files.createTempDirectory("tmpgit").toFile();
        try (Git git = Git.cloneRepository().setDirectory(tmpDir).setURI(url).call()) {
            return tmpDir.toString();
        }
    }
----

[WARNING]
====
When building a native executable, make sure that the link:{quarkus-guides-url}/native-and-ssl#the-truststore-path[SSL support is configured appropriately].
====

== DevServices

JGit starts a link:https://about.gitea.com/[Gitea server] for testing purposes.
The server is started by default when running tests.
To disable it, set the `quarkus.jgit.devservices.enabled` configuration property to `false`.

== Configuration properties

include::./includes/quarkus-jgit.adoc[]
